<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAWovxix\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAWovxix/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAWovxix.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAWovxix\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAWovxix\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AWovxix',
    'container.build_id' => '65137492',
    'container.build_time' => 1612853298,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAWovxix');
