admin:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index
    
base:
    path: /
    controller: App\Controller\BaseController::index

page:
    path: /page/{element}/{page}
    controller: App\Controller\BaseController::page
    requirements:
        element: '\w+'
        page: '\d+'
